export interface StatCategory {
  id: string
  label: string
  statKeys: string[]
}

export const STAT_CATALOG: readonly StatCategory[] = [

  { id: 'pickaxe', label: 'Pickaxe', statKeys: [
    'pickaxe_damage',
    'pickaxe_attack_speed_per_second',
    'pickaxe_radius_percent',
    'pickaxe_crit_chance',
    'pickaxe_crit_damage',
    'pickaxe_super_crit_chance',
    'pickaxe_super_crit_damage',
    'pickaxe_ultra_crit_chance',
    'pickaxe_ultra_crit_damage',
    'pickaxe_omega_crit_chance',
    'pickaxe_omega_crit_damage',
  ] },

  { id: 'bombs', label: 'Bombs', statKeys: [
    'bomb_damage',
    'bomb_crit_chance',
    'bomb_crit_damage',
    'bomb_recharge_speed',
    'bomb_free_chance',
    'bomb_capacity',
    'bomb_additional_multiplier',
    'bomb_super_crit_chance',
    'bomb_super_crit_damage',
    'bomb_ultra_crit_chance',
    'bomb_ultra_crit_damage',
    'bomb_omega_crit_chance',
    'bomb_omega_crit_damage',
    'bomb_cherry3x_chance',
    'bomb_battery_cap_increases',
    'bomb_cap_multiplier',
    'bomb_workshop_cap_increase',
    'bomb_of_plenty_make_gold_chance',
    'bomb_of_plenty_multi',
    'bomb_trans_apply_bop_chance',
    'bomb_transmuter_multi',
  ] },

  { id: 'drones', label: 'Drones', statKeys: [
    'drone_count',
    'drone_damage_percent',
    'drone_radius_percent',
    'drone_movespeed_percent',
    'drone_attack_speed_percent',
    'drone_triple_damage_chance',
    'drone_rapid_fire_chance',
    'drone_suit_cap',
    'coal_generation_seconds',
    'coal_fuel_duration_multi',
    'coal_capacity_multi',
    'coal_fuel_save_chance',
    'coal_drone_exp_multi',
    'void_portal_chance',
    'void_portal_base_multi',
    'golden_void_portal_chance',
    'golden_void_portal_multi',
    'rainbow_void_portal_chance',
    'rainbow_void_portal_multi',
    'elixir_crit_chance',
    'elixir_crit_multi',
  ] },

  { id: 'ores', label: 'Ores', statKeys: [
    'multi_rock_chance',
    'ore_sell_price_multi',
    'ore_income_multi',
    'golden_ore_chance',
    'golden_ore_multi',
    'golden_floor_chance',
    'golden_floor_multi',
    'rainbow_floor_chance',
    'rainbow_floor_multi',
    'galactic_floor_chance',
    'galactic_floor_multi',
    'prismatic_floor_chance',
    'prismatic_floor_multi',
    'pizzas_eaten',
    'steak_eaten',
    'all_floor_multipliers',
  ] },

  { id: 'crafting', label: 'Crafting', statKeys: [
    'free_craft_chance',
    'double_craft_chance',
    'triple_craft_chance',
    'craft_5x_chance',
    'craft_10x_chance',
    'craft_20x_chance',
    'craft_100x_chance',
    'bar_output_multi',
    'bar_upgrade_cost_reduction',
    'bar_craft_cost_multi',
  ] },

  { id: 'obelisk', label: 'Obelisk', statKeys: [
    'obelisk_timer_add',
    'obelisk_cooldown_multi',
    'obelisk_armor_reduction',
  ] },

  { id: 'prestige', label: 'Prestige', statKeys: [
    'xp_level_cap',
    'prestige_point_multi',
    'experience_multi',
    'floor_clear_requirement_multi',
    'artifact_cap_increase',
    'artifact_tier4_cap_increase',
  ] },

  { id: 'lootbugs', label: 'Lootbugs', statKeys: [
    'lootbug_spawn_rate',
    'lootbug_triple_chance',
    'lootbug_golden_chance',
    'lootbug_bank_cap',
    'lootbug_gem_cost_reduction',
    'lootbug_loot_multi',
    'lootfrog_lanterns_used',
  ] },

  { id: 'lootfrogs', label: 'Lootfrogs', statKeys: [
    'lootfrogs_caught',
    'golden_lootfrogs_caught',
    'lootfrog_capacity',
    'lootfrog_loot_multi',
    'lootfrog_golden_chance',
    'lootfrog_golden_multi',
    'lootfrog_triple_spawn_chance',
    'lootfrog_10x_spawn_chance',
    'lootfrog_big_chance',
    'lootfrog_big_multi',
  ] },

  { id: 'chests', label: 'Chests', statKeys: [
    'chest_double_chance',
    'chest_meter_multi',
    'chest_items_bonus',
    'freebie_gems_bonus',
    'freebie_5x_chance',
    'freebie_refresh_chance',
    'freebie_bank_cap',
    'freebie_cooldown_seconds',
    'stonks_chance',
    'stonks_multi',
    'super_stonks_chance',
    'super_stonks_multi',
    'ultra_stonks_chance',
    'ultra_stonks_multi',
  ] },

  { id: 'contracts', label: 'Contracts', statKeys: [
    'contract_cost_reduction',
    'contract_double_points_chance',
    'contract_triple_points_chance',
    'contract_5x_points_chance',
    'contract_10x_points_chance',
    'contract_points_rewarded',
    'contract_cap_increase',
    'contract_upgrade_cost_reduction',
  ] },

  { id: 'veins', label: 'Veins', statKeys: [
    'vein_spawn_rate_multi',
    'vein_income_multi',
    'golden_vein_chance',
    'golden_vein_multi',
    'rainbow_vein_chance',
    'rainbow_vein_multi',
    'gleaming_vein_chance',
    'gleaming_vein_multi',
  ] },

  { id: 'stars', label: 'Stars', statKeys: [
    'star_spawn_rate',
    'star_auto_catch_chance',
    'star_double_spawn_chance',
    'star_triple_spawn_chance',
    'super_star_spawn_multi',
    'super_star_triple_chance',
    'super_star_10x_chance',
    'star_supernova_chance',
    'star_supernova_multi',
    'super_star_supernova_chance',
    'super_star_supernova_multi',
    'star_supergiant_chance',
    'star_supergiant_multi',
    'super_star_supergiant_chance',
    'super_star_supergiant_multi',
    'star_radiant_chance',
    'star_radiant_multi',
    'super_star_radiant_chance',
    'super_star_radiant_multi',
    'all_star_multi',
    'novagiant_combo_multi',
    'candy_eaten',
  ] },

  { id: 'fishing', label: 'Fishing', statKeys: [
    'fishing_rod_power',
    'fishing_drone_capacity',
    'fishing_drone_power',
    'fishing_drone_multiplier',
    'fishing_tier2_dock_multi',
    'fishing_income_multi',
    'fishing_tick_reduction_seconds',
    'fishing_double_tick_chance',
    'fishing_triple_tick_chance',
    'fishing_5x_tick_chance',
    'fishing_token_multi',
    'fishing_notice_requirement',
    'fishing_tiny_notice_chance',
    'fishing_shiny_chance',
    'fishing_shiny_multi',
    'fishing_super_shiny_chance',
    'fishing_super_shiny_multi',
    'fishing_tick_speed',
  ] },

  { id: 'misc', label: 'Misc', statKeys: [
    'game_speed_multi',
    'item_duration_multi',
    'gem_upgrade_cap_increase',
    'pet_levelup_chance_multi',
  ] },

  { id: 'statues', label: 'Statues', statKeys: [
    'statue_0_set1', 'statue_1_set1', 'statue_2_set1',
    'statue_3_set1', 'statue_4_set1', 'statue_5_set1',
    'statue_6_set1', 'statue_7_set1', 'statue_8_set1',
    'statue_0_set2', 'statue_1_set2', 'statue_2_set2',
    'statue_3_set2', 'statue_4_set2', 'statue_5_set2',
    'statue_6_set2', 'statue_7_set2', 'statue_8_set2',
    'statue_0_set3', 'statue_1_set3', 'statue_2_set3',
    'statue_3_set3', 'statue_4_set3', 'statue_5_set3',
    'statue_6_set3', 'statue_7_set3', 'statue_8_set3',
  ] },
]

// Statue-specific enrichment table: name + world per statKey.
// Source: `Copy of JSON Tablifier.xlsx` columns P/Q rows 4–30.
export interface StatueEnrichment {
  name: string
  world: 1 | 3 | 4
}

export const STATUE_ENRICHMENT: Readonly<Record<string, StatueEnrichment>> = {
  statue_0_set1: { name: 'Rhythm',        world: 1 },
  statue_1_set1: { name: 'Awareness',    world: 1 },
  statue_2_set1: { name: 'Slaying',      world: 1 },
  statue_3_set1: { name: 'Appetite',     world: 1 },
  statue_4_set1: { name: 'Friendship',   world: 1 },
  statue_5_set1: { name: 'Hygiene',      world: 1 },
  statue_6_set1: { name: 'Artistry',     world: 1 },
  statue_7_set1: { name: 'Randomness',   world: 1 },
  statue_8_set1: { name: 'Childhood',    world: 1 },
  statue_0_set2: { name: 'Craftsmanship', world: 3 },
  statue_1_set2: { name: 'Propulsion',   world: 3 },
  statue_2_set2: { name: 'Safety',       world: 3 },
  statue_3_set2: { name: 'Ignition',     world: 3 },
  statue_4_set2: { name: 'Warmth',       world: 3 },
  statue_5_set2: { name: 'Feline',       world: 3 },
  statue_6_set2: { name: 'Affluence',    world: 3 },
  statue_7_set2: { name: 'Eastwood',     world: 3 },
  statue_8_set2: { name: 'Soprano',      world: 3 },
  statue_0_set3: { name: 'Comfort',      world: 4 },
  statue_1_set3: { name: 'Timekeeping',  world: 4 },
  statue_2_set3: { name: 'Combat',       world: 4 },
  statue_3_set3: { name: 'Nature',       world: 4 },
  statue_4_set3: { name: 'Semblance',    world: 4 },
  statue_5_set3: { name: 'Crochet',      world: 4 },
  statue_6_set3: { name: 'Antagonism',   world: 4 },
  statue_7_set3: { name: 'Fallacy',      world: 4 },
  statue_8_set3: { name: 'Rodentia',     world: 4 },
}

// State labels driven by the raw integer value 0/1/2/3.
// Source: in-game build state for each statue tier.
export const STATUE_STATE_LABELS = ['Unbuilt', 'Normal', 'Gilded', 'Platinized'] as const
